### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by trechriron** [ofkindness/generator-express-es6#22]
I have a default install with a few added less files. Just getting started.

I'm getting this Error when I load the page (it does not prevent the page view);

```
GET / 304 98.055 ms - -
GET /stylesheets/style.css 200 420.798 ms - 3706
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\express\lib\response.js:170:12)
    at done (D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\express\lib\response.js:1004:10)
    at D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\hbs\lib\hbs.js:114:11
    at Object.done (D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\hbs\lib\async.js:74:20)
    at D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\hbs\lib\hbs.js:109:20
    at D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\hbs\lib\hbs.js:90:11
    at Object.done (D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\hbs\lib\async.js:74:20)
    at D:\Berge\My Documents\Workspace\hero6e_online_tools\node_modules\hbs\lib\hbs.js:85:20
```

The stacktrace points to native modules. After some research, it seems the app is sending header twice or more. With the simple boilerplate, I can't figure out WHERE it's dong it? Is this a dependency issue?

**Comment by ofkindness** [comment]
Hello @trechriron I can't reproduce the issue. Can you provide more details?
